### ISSUE TITLE
Good job and very helpful!

### ISSUE THREAD

**Issue by fdege** [crevillo/ezsocialloginbundle#10]
Hi Crevillo,

we tested the bundle on a eZ 5.4.5 system /Symfony stack) and it works for this version as well! 
What do you think regarding the dependencies which is 6 or higher right now. A version 5.4.5 or higher should work as well and it might make sense to lower the restrictions.
What do you think?

We were able to set it up for facebook with this configuration:
`hwi_oauth:
    firewall_names: [ezpublish_front]
    resource_owners:
      facebook:
        type: facebook
        client_id: %facebook_id%
        client_secret: %facebook_secret%
        scope: "email"
        infos_url:     "https://graph.facebook.com/me?fields=id,name,email"
        paths:
           email:          email`

There might be one issue with Facebook if you did not have published your app yet since in this case no email is provided by facebook (unless you use a test user). In this case creating the user fails with an exception. It might be usefull to add checks (i am not sure if other providers might return an empty email even after a successful login). 

Greetings from Berlin!

**Comment by crevillo** [comment]
Hi @fdege and thanks for your words :). 

About lowering requirements, you're totally right. It should work well with 5.4 and maybe even lower. If you have tested and want to send a pull request with this change i'll be more than happy to merge it :). I just started from other ez publish bundle and the composer was merely copy-pasted at first :)
Let me know if you will try this pr and if not, i'll try to work on this in the next days. 

About facebook: Not exactlyl the same case but still similar, Twitter doesn't send you the user e-mail at all. This is why i added this https://github.com/crevillo/ezsocialloginbundle/blob/master/src/Crevillo/EzSocialLoginBundle/OAuth/Response/TwitterUserResponse.php. I mean, you can override methods from hwi oauthbundle and maybe fit your needs. in this twitter case, as twitter doesn't send me the user email i just get the username and add dummy thing to complete the email. 

maybe you could take this an example. Be aware you will need to override the twitter (facebook in your case) resource owner provided by the HwiOauth Bundle. Something like this https://github.com/crevillo/ezsocialloginbundle/blob/master/src/Crevillo/EzSocialLoginBundle/OAuth/ResourceOwner/TwitterResourceOwner.php

You just need to override the configureOptions method in other to tell your resource that your response class will be another one. 

Once the class is created, is only a matter of redining hwi class parameters so these parameteres became class of your bundle https://github.com/crevillo/ezsocialloginbundle/blob/master/src/Crevillo/EzSocialLoginBundle/Resources/config/services.yml

Of course you can do this from your own bundle too. 

Greetings from Madrid!

**Comment by silverjgo** [comment]
Hello @crevillo,

I saw you already merged the alternate dependency to eZ 5.4.x into the master branch. But there is no version tag, yet. Thus, people would be forced to depend on master or the specific commit, in order to install this bundle within an eZ 5 application. Is it because of the failed build or what would be necessary for a version bump?

Thanks and best regards,
Jens

**Comment by Tantacom** [comment]
@silverjgo thanks for your comment. i'll tag this, my fault. 
btw, i'm @crevillo , just with annoter account ;)

**Comment by crevillo** [comment]
tagged as 1.0.0 as looks to be stable enough. let me know if this works for you.

**Comment by silverjgo** [comment]
Thank you very much for your quick response. :-) I made a quick test with composer and it worked for the ezsocialloginbundle, no complaints about version mismatch any longer.
